---
- name: Check if route map is applied
  shell: vtysh -c "show run" | grep prepend | wc -l
  register: prepend_count

- name: Apply maintenance route map
  command: net add bgp neighbor FABRIC route-map MAINTENANCE_MODE out
  when: prepend_count.stdout | int < 3

- name: Commit the change
  command: net commit
  when: prepend_count.stdout | int < 3

- name: Verify traffic is drained. This will take a moment...
  interface_stats:

- name: Reboot!
  shell: sleep 2 && shutdown -r now "Ansible reboot triggered"
  async: 1
  poll: 0
  ignore_errors: true

- name: Wait for leaf to restore. Please stand by...
  wait_for: >
    host="{{ inventory_hostname }}"
    port="{{ ansible_port }}"
    delay=30
    timeout=180
  delegate_to: localhost
  become: false

# This is mainly to let netd start
- name: Give services time to start 
  pause: 
    seconds: 30

- name: load vars
  include_vars: group_vars/all

- name: Remove routemap
  command: net del bgp neighbor FABRIC route-map MAINTENANCE_MODE out

- name: Commit the change
  command: net commit
