---
- name: Copy Quagga daemons file
  copy: 
    src: daemons 
    dest: /etc/frr/daemons 
    backup: yes
  notify: restart frr

# - name: Add Cumulus Repo
#   apt_repository:
#     repo: deb http://apps3.cumulusnetworks.com/repos/deb CumulusLinux-3 netq-1.1
#     state: present
#     update_cache: no

# - name: Install NetQ
#   apt:
#     name: cumulus-netq
#     update_cache: yes
#   register: install_netq

# - name: Restart Rsyslog
#   service:
#     name: rsyslog
#     state: restarted
#   when: install_netq.changed

# - name: Add netq server IP
#   command: netq config add server 192.168.0.254
#   when: install_netq.changed

# - name: Restart NetQ Agent
#   command: netq config agent restart
#   when: install_netq.changed
